# 可以通过 debug=true来查看，哪些自动配置类生效，哪些没有生效！
debug: true



# 配置文件到底能写什么 ---联系--- spring.factories;
# 在我们这配置文件中能配置的东西，都存在固有规律
# xxxAutoConfiguration:默认值   xxxProperties 和 配置文件绑定，我们就可以使用自定义的配置了！
#spring:
#  mvc:
#    date-format :



## 横线分割已过时
#
#server:
#  port: 8081
##spring:
##  profiles:
##    active: dev
#
#---
#server:
#  port: 8082
#spring:
#  profiles: dev
#
#---
#server:
#  port: 8083
#spring:
#  profiles: test
#
#---



#server:
#  port: 8084
person:
  # 没改get、set方法名，松散绑定失败
  name: qinjiang${random.uuid}
  age: ${random.int}
  happy: false
  birth: 2019/11/02
  maps: {k1: v1,k2: v2}
  hello: happy
  lists:
    - code
    - music
    - girl
  dog:
    firstName: ${person.hello:hello}_旺财
    age: 3


dog:
  first-name: 阿黄
  age: 3








## k=v
## 对空格的要求十分高！
## 普通的key-value
#
## 注入到我们的配置类中！
#
#name: qinjiang
#
## 对象
#student1:
#  name: qinjiang
#  age: 3
#
## 行内写法
#
#student2: {name: qinjiang,age: 3}
#
## 数组
#pets1:
#  - cat
#  - dog
#  - pig
#
#pets2: [cat,dog,pig]