person:
  last-name: qinjiang${random.uuid}
  age: ${random.int}
  happy: false
  birth: 2019/11/02
  maps: {k1: v1,k2: v2}
  hello: happy
  lists:
    - code
    - music
    - girl
  dog:
    name: ${person.hello:hello}_旺财
    age: 3


dog:
  first-name: 阿黄
  age: 3








## k=v
## 对空格的要求十分高！
## 普通的key-value
#
## 注入到我们的配置类中！
#
#name: qinjiang
#
## 对象
#student1:
#  name: qinjiang
#  age: 3
#
## 行内写法
#
#student2: {name: qinjiang,age: 3}
#
## 数组
#pets1:
#  - cat
#  - dog
#  - pig
#
#pets2: [cat,dog,pig]